"""empty message

Revision ID: 12634106e899
Revises: 003d99f76515
Create Date: 2024-05-17 19:31:13.817991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12634106e899'
down_revision = '003d99f76515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.drop_constraint('portfolio_user_fkey', type_='foreignkey')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.create_foreign_key('portfolio_user_fkey', 'user', ['user'], ['id'])

    # ### end Alembic commands ###
