"""Add tasting columns, New flavor table

Revision ID: 1ad63b86c1db
Revises: 998492755939
Create Date: 2024-02-17 20:17:58.761897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad63b86c1db'
down_revision = '998492755939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flavor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adjective', sa.String(), nullable=False))

    with op.batch_alter_table('flavor_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adjective_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('coffee_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('acidity_id', sa.String(), nullable=False))
        batch_op.create_foreign_key(None, 'coffee', ['coffee_id'], ['id'])
        batch_op.create_foreign_key(None, 'flavor', ['adjective_id'], ['id'])

    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.drop_column('rating')

    with op.batch_alter_table('flavor_profile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('acidity_id')
        batch_op.drop_column('coffee_id')
        batch_op.drop_column('adjective_id')

    with op.batch_alter_table('flavor', schema=None) as batch_op:
        batch_op.drop_column('adjective')

    # ### end Alembic commands ###
