"""Initial migration

Revision ID: 2836e2395e7b
Revises: 
Create Date: 2024-02-15 20:50:21.992588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2836e2395e7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coffee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_process', sa.String(), nullable=True))
        batch_op.drop_column('tasting_notes')
        batch_op.drop_column('process')

    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tasting_notes', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.drop_column('tasting_notes')

    with op.batch_alter_table('coffee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('process', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tasting_notes', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('_process')

    # ### end Alembic commands ###
