"""Add tasting columns, New flavor table

Revision ID: 5474d2d4b1d3
Revises: 1ad63b86c1db
Create Date: 2024-02-17 20:21:52.565555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5474d2d4b1d3'
down_revision = '1ad63b86c1db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flavor_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acidity', sa.String(), nullable=False))
        batch_op.drop_column('acidity_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flavor_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acidity_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('acidity')

    # ### end Alembic commands ###
