"""column name change

Revision ID: 5559bf596558
Revises: 2836e2395e7b
Create Date: 2024-02-15 20:57:44.307131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5559bf596558'
down_revision = '2836e2395e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coffee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('process_method', sa.String(), nullable=True))
        batch_op.drop_column('_process')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coffee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_process', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('process_method')

    # ### end Alembic commands ###
