"""Changed boolfield to radio

Revision ID: 998492755939
Revises: 5559bf596558
Create Date: 2024-02-16 14:26:03.552377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998492755939'
down_revision = '5559bf596558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coffee', schema=None) as batch_op:
        batch_op.alter_column('blend',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coffee', schema=None) as batch_op:
        batch_op.alter_column('blend',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###
